openapi: 3.2.0
info:
  version: 0.0.9
  title: 'OpenAPI Specification: Merchant Product Attributes API'
  description: This service enumerates and describes Zalando product attributes.
  x-audience: external-merchant
  x-api-id: 84689b31-793f-4583-91e5-9ab195be36ca
tags:
- name: Attributes
paths:
  /merchants/{merchant_id}/attribute-types/{type_label}/attributes:
    get:
      summary: List all attributes of the given attribute type
      tags:
      - Attributes
      security:
      - OAuth2:
        - products/attributes/read
      parameters:
      - $ref: '#/components/parameters/merchant_id'
      - $ref: '#/components/parameters/type_label'
      - $ref: '#/components/parameters/flow_id'
      responses:
        '200':
          $ref: '#/components/responses/AttributesPagedResponse'
        default:
          $ref: '#/components/responses/GenericError'
  /merchants/{merchant_id}/attribute-types/{type_label}/attributes/{attribute_label}:
    get:
      summary: Return a given attribute of the given attribute type
      tags:
      - Attributes
      security:
      - OAuth2:
        - products/attributes/read
      parameters:
      - $ref: '#/components/parameters/merchant_id'
      - $ref: '#/components/parameters/type_label'
      - $ref: '#/components/parameters/attribute_label'
      - $ref: '#/components/parameters/flow_id'
      responses:
        '200':
          $ref: '#/components/responses/AttributeResponse'
        default:
          $ref: '#/components/responses/GenericError'
components:
  schemas:
    AttributeMeta:
      type: object
      description: 'Optional additional information for the attribute.

        There are no guarantees or fixed structure on this field.

        '
    Name:
      description: 'Map of language to text, key must follow (rfc-2616, section

        3.10)[https://tools.ietf.org/html/rfc2616#section-3.10]


        This mapping is only a human readable name of the entity.

        Building logic dependant on this field should be avoided.

        '
      additionalProperties:
        type: string
      example:
        en: The name
        de: Der Name
        es: El nombre
    AttributeValue:
      description: 'Holder for the value of an attribute.


        There must be one, and only one, of the following properties set, and

        this **must** match the definition of the Attribute''s `Type.definition`.

        '
      properties:
        boolean:
          type: boolean
        datetime:
          type: string
          format: date-time
        decimal:
          type: number
          format: float
        integer:
          type: integer
          format: int64
        string:
          type: string
        localized:
          type: object
          additionalProperties:
            type: string
        structure:
          type: object
      example:
        localized:
          fr: gris foncé
          pt: cinzento escuro
          cs: tmavě šedá
          it: grigio scuro
          nl: Donkergrijs
          de: dunkelgrau
          sv: mörkgrå
          da: mørkegrå
          en: dark grey
          es: gris oscuro
          fi: tummanharmaa
          'no': mørkegrå
          pl: ciemnoszary
    Attribute:
      required:
      - label
      - value
      - name
      properties:
        label:
          type: string
          example: color_code
        name:
          $ref: '#/components/schemas/Name'
        value:
          $ref: '#/components/schemas/AttributeValue'
        _meta:
          $ref: '#/components/schemas/AttributeMeta'
  parameters:
    flow_id:
      name: X-Flow-Id
      description: 'A custom header that will be passed onto any further requests and can be

        used for diagnosing.

        '
      in: header
      required: false
      schema:
        type: string
    type_label:
      name: type_label
      in: path
      description: Label of the attribute type
      required: true
      schema:
        type: string
        format: string
    merchant_id:
      name: merchant_id
      in: path
      description: Id of the merchant
      required: true
      schema:
        type: string
        format: string
    attribute_label:
      name: attribute_label
      in: path
      description: Label of the attribute
      required: true
      schema:
        type: string
        format: string
  responses:
    AttributesPagedResponse:
      description: list of attributes
      content:
        application/json:
          schema:
            required:
            - items
            properties:
              items:
                type: array
                items:
                  $ref: '#/components/schemas/Attribute'
    GenericError:
      description: 'error occurred - see status code and problem object for more

        information.

        '
      content:
        application/problem+json:
          schema:
            $ref: https://opensource.zalando.com/problem/schema.yaml#/Problem
    AttributeResponse:
      description: a single attribute
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Attribute'
  securitySchemes:
    merchant_platform:
      type: oauth2
      description: The Products service uses the OpenID Connect (OIDC) authentication layer of OAuth 2 to handle the client credentials process flow.
      flows:
        clientCredentials:
          tokenUrl: https://api-sandbox.merchants.zalando.com/auth/token
          scopes:
            products/attributes/read: scope to read a product
