openapi: 3.2.0
info:
  version: '1.1'
  title: 'OpenAPI Specification: Products Discovery API'
  description: This specification describes the Products API of the Zalando Merchant Platform.
  x-audience: external-merchant
  x-api-id: 49e51b92-1b36-447f-adb1-be1305faaea6
tags:
- name: Discovery API
paths:
  /products/identifiers/{ean}:
    get:
      summary: 'Look up the existing product details in Zalando platform

        '
      tags:
      - Discovery API
      security:
      - OAuth2:
        - lemur.prototype.read
      parameters:
      - $ref: '#/components/parameters/ean'
      responses:
        '200':
          $ref: '#/components/responses/LookUpResponse'
        '409':
          $ref: '#/components/responses/ConflictError'
        default:
          $ref: '#/components/responses/GenericError'
components:
  responses:
    LookUpResponse:
      description: 'Successfully looked up product detail information

        '
      content:
        application/json;charset=utf-8:
          schema:
            $ref: '#/components/schemas/LookUp'
    ConflictError:
      description: The request is semantically correct, but it cannot be processed due to business reasons. e.g. A product with same id was already submitted. Please refer to the response.
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Problem'
    GenericError:
      description: Error occurred - see status code and problem object for more information.
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Problem'
  schemas:
    LookUp:
      properties:
        items:
          type: array
          items:
            properties:
              ean:
                $ref: '#/components/schemas/EAN'
      example:
        items:
        - ean: '9780679762881'
    EAN:
      description: The International Article Number or also known as European Article Number.
      type: string
      format: gtin13
      example: '9780679762881'
    Problem:
      properties:
        type:
          type: string
          format: uri
          description: 'An absolute URI that identifies the problem type. When dereferenced,

            it SHOULD provide human-readable documentation for the problem type

            (e.g., using HTML).

            '
          default: about:blank
        title:
          type: string
          description: 'A short, summary of the problem type. Written in English and readable

            for engineers (usually not suited for non technical stakeholders and

            not localized);

            '
        status:
          type: integer
          format: int32
          description: 'The HTTP status code generated by the origin server for this occurrence

            of the problem.

            '
          minimum: 100
          exclusiveMaximum: 600
        detail:
          type: string
          description: 'A human readable explanation specific to this occurrence of the

            problem.

            '
        instance:
          type: string
          format: uri
          description: 'An absolute URI that identifies the specific occurrence of the problem.

            It may or may not yield further information if dereferenced.

            '
      example:
        type: https://zalando.github.io/problem/constraint-violation
        title: Service Unavailable
        status: 503
        detail: Connection to database timed out
  parameters:
    ean:
      name: ean
      in: path
      description: The International Article Number or also known as European Article Number.
      required: true
      schema:
        $ref: '#/components/schemas/EAN'
  securitySchemes:
    merchant_platform:
      type: oauth2
      description: The Products service uses the OpenID Connect (OIDC) authentication layer of OAuth 2 to handle the client credentials process flow.
      flows:
        clientCredentials:
          tokenUrl: https://api-sandbox.merchants.zalando.com/auth/token
          scopes:
            products/read: scope to read a product
            products/write: scope to create or update a product
